#!/bin/bash

gcloud auth activate-service-account --key-file=/etc/auth/snapadmin.json

INSTANCE_NAME=redash-prd
SNAPSHOT_ZONE_NAME=asia-northeast1-c

if [ `date -d '1 day' +'%d'` = "01" ];then 
    gcloud compute disks snapshot -q ${INSTANCE_NAME} --zone=${SNAPSHOT_ZONE_NAME} --snapshot-names=${INSTANCE_NAME}-`date +'%Y%m'` 
fi 

for i in `seq 8 14`;do 
    gcloud compute snapshots delete -q ${INSTANCE_NAME}-`date -d "${i} days ago" +'%Y%m%d'` 
done 

gcloud compute disks snapshot -q ${INSTANCE_NAME} --zone=${SNAPSHOT_ZONE_NAME} --snapshot-names=${INSTANCE_NAME}-`date +'%Y%m%d'` 
